"""init

Revision ID: 9e474889081c
Revises: 
Create Date: 2024-06-22 20:08:25.738493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e474889081c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('origins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('character_name', sa.String(length=25), nullable=False),
    sa.Column('origin', sa.String(length=25), nullable=False),
    sa.Column('race', sa.String(length=25), nullable=False),
    sa.Column('sub_race', sa.String(length=25), nullable=True),
    sa.Column('background', sa.String(length=25), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('constitution', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('wisdom', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.Column('plus_1', sa.String(length=20), nullable=False),
    sa.Column('plus_2', sa.String(length=20), nullable=False),
    sa.Column('helmet', sa.Integer(), nullable=True),
    sa.Column('cloak', sa.Integer(), nullable=True),
    sa.Column('armor', sa.Integer(), nullable=True),
    sa.Column('gloves', sa.Integer(), nullable=True),
    sa.Column('boots', sa.Integer(), nullable=True),
    sa.Column('amulet', sa.Integer(), nullable=True),
    sa.Column('ring_1', sa.Integer(), nullable=True),
    sa.Column('ring_2', sa.Integer(), nullable=True),
    sa.Column('main_hand', sa.Integer(), nullable=True),
    sa.Column('off_hand', sa.Integer(), nullable=True),
    sa.Column('ranged_mh', sa.Integer(), nullable=True),
    sa.Column('ranged_oh', sa.Integer(), nullable=True),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amulet'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['armor'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['boots'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['cloak'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['gloves'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['helmet'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['main_hand'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['off_hand'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['ranged_mh'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['ranged_oh'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['ring_1'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['ring_2'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('build_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('sub_class', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('comments')
    op.drop_table('build_classes')
    op.drop_table('builds')
    op.drop_table('users')
    op.drop_table('races')
    op.drop_table('origins')
    op.drop_table('equipment')
    op.drop_table('classes')
    # ### end Alembic commands ###
