"""init

Revision ID: 51c9104e3e06
Revises: 
Create Date: 2024-09-04 18:50:53.199419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c9104e3e06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amulets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('rarity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('modifiers', sa.String(length=100), nullable=True),
    sa.Column('spell', sa.String(length=50), nullable=True),
    sa.Column('img', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('armours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('rarity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('modifiers', sa.String(length=100), nullable=True),
    sa.Column('spell', sa.String(length=50), nullable=True),
    sa.Column('armour_class', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('backgrounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('boots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('rarity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('modifiers', sa.String(length=100), nullable=True),
    sa.Column('spell', sa.String(length=50), nullable=True),
    sa.Column('img', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cantrips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('school', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('range', sa.Integer(), nullable=False),
    sa.Column('radius', sa.Integer(), nullable=True),
    sa.Column('attack_save', sa.String(length=3), nullable=True),
    sa.Column('damage', sa.String(length=10), nullable=True),
    sa.Column('damage_type', sa.String(length=10), nullable=True),
    sa.Column('concentration', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('modifier', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cloaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('rarity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('modifiers', sa.String(length=100), nullable=True),
    sa.Column('spell', sa.String(length=50), nullable=True),
    sa.Column('img', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gloves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('rarity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('modifiers', sa.String(length=100), nullable=True),
    sa.Column('spell', sa.String(length=50), nullable=True),
    sa.Column('img', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('helmets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('rarity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('modifiers', sa.String(length=100), nullable=True),
    sa.Column('spell', sa.String(length=50), nullable=True),
    sa.Column('img', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('origins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('rarity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('modifiers', sa.String(length=100), nullable=True),
    sa.Column('spell', sa.String(length=50), nullable=True),
    sa.Column('img', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('weapons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('range', sa.String(length=6), nullable=False),
    sa.Column('rarity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('modifiers', sa.String(length=100), nullable=True),
    sa.Column('spell', sa.String(length=50), nullable=True),
    sa.Column('damage', sa.String(length=50), nullable=True),
    sa.Column('damage_bonus', sa.Integer(), nullable=False),
    sa.Column('damage_type', sa.String(length=50), nullable=True),
    sa.Column('damage_mod', sa.String(length=50), nullable=True),
    sa.Column('img', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('character_name', sa.String(length=25), nullable=False),
    sa.Column('origin', sa.Integer(), nullable=False),
    sa.Column('race', sa.Integer(), nullable=False),
    sa.Column('sub_race', sa.String(length=20), nullable=True),
    sa.Column('background', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('constitution', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('wisdom', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.Column('plus_1', sa.String(length=20), nullable=False),
    sa.Column('plus_2', sa.String(length=20), nullable=False),
    sa.Column('helmet', sa.Integer(), nullable=True),
    sa.Column('cloak', sa.Integer(), nullable=True),
    sa.Column('armour', sa.Integer(), nullable=True),
    sa.Column('glove', sa.Integer(), nullable=True),
    sa.Column('boot', sa.Integer(), nullable=True),
    sa.Column('amulet', sa.Integer(), nullable=True),
    sa.Column('ring_1', sa.Integer(), nullable=True),
    sa.Column('ring_2', sa.Integer(), nullable=True),
    sa.Column('melee_mh', sa.Integer(), nullable=True),
    sa.Column('melee_oh', sa.Integer(), nullable=True),
    sa.Column('ranged_mh', sa.Integer(), nullable=True),
    sa.Column('ranged_oh', sa.Integer(), nullable=True),
    sa.Column('armour_class', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amulet'], ['amulets.id'], ),
    sa.ForeignKeyConstraint(['armour'], ['armours.id'], ),
    sa.ForeignKeyConstraint(['background'], ['backgrounds.id'], ),
    sa.ForeignKeyConstraint(['boot'], ['boots.id'], ),
    sa.ForeignKeyConstraint(['cloak'], ['cloaks.id'], ),
    sa.ForeignKeyConstraint(['glove'], ['gloves.id'], ),
    sa.ForeignKeyConstraint(['helmet'], ['helmets.id'], ),
    sa.ForeignKeyConstraint(['melee_mh'], ['weapons.id'], ),
    sa.ForeignKeyConstraint(['melee_oh'], ['weapons.id'], ),
    sa.ForeignKeyConstraint(['origin'], ['origins.id'], ),
    sa.ForeignKeyConstraint(['race'], ['races.id'], ),
    sa.ForeignKeyConstraint(['ranged_mh'], ['weapons.id'], ),
    sa.ForeignKeyConstraint(['ranged_oh'], ['weapons.id'], ),
    sa.ForeignKeyConstraint(['ring_1'], ['rings.id'], ),
    sa.ForeignKeyConstraint(['ring_2'], ['rings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('build_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('sub_class', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('modifier', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=140), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('build_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('comments')
    op.drop_table('build_classes')
    op.drop_table('builds')
    op.drop_table('weapons')
    op.drop_table('users')
    op.drop_table('rings')
    op.drop_table('races')
    op.drop_table('origins')
    op.drop_table('helmets')
    op.drop_table('gloves')
    op.drop_table('cloaks')
    op.drop_table('classes')
    op.drop_table('cantrips')
    op.drop_table('boots')
    op.drop_table('backgrounds')
    op.drop_table('armours')
    op.drop_table('amulets')
    # ### end Alembic commands ###
